version: '2.2'

services:
  postgresqlalpha:
    image: ${DOCKER_IMAGE}
    volumes:
    - postgres-alpha_data:/var/lib/postgresql/data
    - ./config/timescaledb/99_timescaledb.yml:/config/patroni/99_timescaledb.yml
    ports:
    - 0.0.0.0::5432
    - 0.0.0.0::8008
    depends_on:
    - consul
    environment:
    - PGDATA=/var/lib/postgresql/data/PGDATA
    - PATRONI_NAME=postgresqlalpha
    - PATRONI_SCOPE=alfdb
    - PATRONI_POSTGRESQL_CONNECT_ADDRESS=postgresqlalpha:5432
    - PATRONI_RESTAPI_CONNECT_ADDRESS=postgresqlalpha:8008
    - PATRONI_SUPERUSER_USERNAME=postgres
    - PATRONI_SUPERUSER_PASSWORD=postgres
    - DB_NAME=promscale
    - DB_ADMIN=promadmin
    - DB_PW=prompw
    - PROMSCALE_INIT=true
    - PROMSCALE_DEFAULT_CHUNK_INTERVAL=2 hours

  postgresqlbravo:
    image: ${DOCKER_IMAGE}
    volumes:
    - postgres-bravo_data:/var/lib/postgresql/data
    - ./config/timescaledb/99_timescaledb.yml:/config/patroni/99_timescaledb.yml
    ports:
    - 0.0.0.0::5432
    - 0.0.0.0::8008
    depends_on:
    - consul
    environment:
    - PGDATA=/var/lib/postgresql/data/PGDATA
    - PATRONI_NAME=postgresqlbravo
    - PATRONI_SCOPE=alfdb
    - PATRONI_POSTGRESQL_CONNECT_ADDRESS=postgresqlbravo:5432
    - PATRONI_RESTAPI_CONNECT_ADDRESS=postgresqlbravo:8008
    - PATRONI_SUPERUSER_USERNAME=postgres
    - PATRONI_SUPERUSER_PASSWORD=postgres
    - DB_NAME=promscale
    - DB_ADMIN=promadmin
    - DB_PW=prompw
    - PROMSCALE_INIT=true
    - PROMSCALE_DEFAULT_CHUNK_INTERVAL=2 hours

  consul:
    image: consul:1.5.3
    ports:
    - 0.0.0.0::8500
    command: agent -data-dir /consul/data -server -bootstrap -ui -client 0.0.0.0

volumes:
  postgres-alpha_data:
  postgres-bravo_data:
