#!/bin/bash

echo psql "$@" -c "CREATE EXTENSION IF NOT EXISTS timescaledb WITH VERSION '$TIMESCALEDB_VERSION' CASCADE;"
psql "$@" -c "CREATE EXTENSION IF NOT EXISTS timescaledb WITH VERSION '$TIMESCALEDB_VERSION' CASCADE;"

